//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBitacoras
    {
        public decimal decIdBitacora { get; set; }
        public decimal decIdUsuario { get; set; }
        public Nullable<System.DateTime> datFechaOperacion { get; set; }
        public string strOperacion { get; set; }
        public string strTipoRegistro { get; set; }
        public string decNumRegistro { get; set; }
    
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
