//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfiguracion
    {
        public decimal decIdConfiguracion { get; set; }
        public Nullable<int> intMoneda { get; set; }
        public string strNombreEmpresa { get; set; }
        public string strDireccionEmpresa { get; set; }
        public string strTelefono { get; set; }
        public string strRUCEmpresa { get; set; }
        public string strPieEmpresa { get; set; }
        public string strEsloganEmpresa { get; set; }
        public string strDireccionLogo { get; set; }
        public string strChequeNombreDe { get; set; }
        public Nullable<decimal> decPorcentajeIVA { get; set; }
        public string strRutaFoto { get; set; }
        public Nullable<bool> bitImprimirFacturaUS { get; set; }
        public Nullable<decimal> decItemsXFactura { get; set; }
        public Nullable<decimal> decRetencionIR { get; set; }
        public Nullable<decimal> decRetencionAlcaldia { get; set; }
        public Nullable<decimal> decDigitosVenta { get; set; }
        public Nullable<int> intIdPrecio { get; set; }
        public string strHost { get; set; }
        public Nullable<int> intPort { get; set; }
    
        public virtual tblMonedas tblMonedas { get; set; }
        public virtual tblPrecios tblPrecios { get; set; }
    }
}
