//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCotizaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCotizaciones()
        {
            this.tblDetalleCotizaciones = new HashSet<tblDetalleCotizaciones>();
        }
    
        public decimal decIdCotizacion { get; set; }
        public string strNumCotizacion { get; set; }
        public Nullable<decimal> decIdCliente { get; set; }
        public Nullable<decimal> decIdContacto { get; set; }
        public Nullable<decimal> decIdVendedor { get; set; }
        public Nullable<decimal> decIdUsuario { get; set; }
        public System.DateTime datFechaCreacion { get; set; }
        public Nullable<decimal> decSubtotal { get; set; }
        public Nullable<decimal> decIva { get; set; }
        public Nullable<decimal> decDescuento { get; set; }
        public string strObservaciones { get; set; }
        public string strInfAdicional { get; set; }
        public Nullable<int> intEstadoCotizacion { get; set; }
        public Nullable<bool> bitFactura { get; set; }
        public Nullable<System.DateTime> datFechaVencimiento { get; set; }
    
        public virtual tblClientes tblClientes { get; set; }
        public virtual tblClientesContacto tblClientesContacto { get; set; }
        public virtual tblVendedores tblVendedores { get; set; }
        public virtual tblUsuarios tblUsuarios { get; set; }
        public virtual tblEstados tblEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetalleCotizaciones> tblDetalleCotizaciones { get; set; }
    }
}
