//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientesContacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClientesContacto()
        {
            this.tblCotizaciones = new HashSet<tblCotizaciones>();
        }
    
        public decimal decIdContacto { get; set; }
        public decimal decIdCliente { get; set; }
        public string strNombreContacto { get; set; }
        public string strTelefono { get; set; }
        public string strExtension { get; set; }
        public string strCelular { get; set; }
        public string strCorreo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCotizaciones> tblCotizaciones { get; set; }
        public virtual tblClientes tblClientes { get; set; }
    }
}
