//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetalleCotizaciones
    {
        public decimal decIdDetalle { get; set; }
        public decimal decIdCotizacion { get; set; }
        public decimal decIdProducto { get; set; }
        public Nullable<decimal> decCantidad { get; set; }
        public Nullable<decimal> decCosto { get; set; }
        public Nullable<decimal> decMargen { get; set; }
        public Nullable<decimal> decPrecio { get; set; }
        public Nullable<decimal> decDescuento { get; set; }
        public Nullable<decimal> decIdProveedor { get; set; }
        public Nullable<bool> bitExonerado { get; set; }
        public Nullable<decimal> decIdUsuario { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
    
        public virtual tblCotizaciones tblCotizaciones { get; set; }
        public virtual tblProductos tblProductos { get; set; }
        public virtual tblUsuarios tblUsuarios { get; set; }
        public virtual tblProveedores tblProveedores { get; set; }
    }
}
