//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblErrores
    {
        public decimal decIdError { get; set; }
        public string strError { get; set; }
        public Nullable<decimal> decIdFormulario { get; set; }
        public string strStackTrace { get; set; }
        public Nullable<decimal> decIdUsuario { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
    
        public virtual tblFormularios tblFormularios { get; set; }
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
