//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProveedores()
        {
            this.tblProductosXProveedor = new HashSet<tblProductosXProveedor>();
            this.tblDetalleCotizaciones = new HashSet<tblDetalleCotizaciones>();
        }
    
        public decimal decIdProveedor { get; set; }
        public string strNombre { get; set; }
        public string strDireccion { get; set; }
        public string strTelefono { get; set; }
        public Nullable<bool> bitExonerado { get; set; }
        public string strRUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductosXProveedor> tblProductosXProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetalleCotizaciones> tblDetalleCotizaciones { get; set; }
    }
}
