//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductos()
        {
            this.tblProductosXProveedor = new HashSet<tblProductosXProveedor>();
            this.tblDetalleCotizaciones = new HashSet<tblDetalleCotizaciones>();
        }
    
        public decimal decIdProducto { get; set; }
        public string strProducto { get; set; }
        public string strReferencia { get; set; }
        public Nullable<decimal> decCosto { get; set; }
        public Nullable<decimal> decPrecio1 { get; set; }
        public Nullable<decimal> decPrecio2 { get; set; }
        public Nullable<decimal> decPrecio3 { get; set; }
        public Nullable<int> intMoneda { get; set; }
        public Nullable<decimal> decExistencia { get; set; }
        public Nullable<bool> bitNoExistencia { get; set; }
        public bool bitActivo { get; set; }
        public Nullable<bool> bitExonerado { get; set; }
        public Nullable<decimal> decIdTipoProducto { get; set; }
        public Nullable<int> intIdPrecio { get; set; }
    
        public virtual tblMonedas tblMonedas { get; set; }
        public virtual tblPrecios tblPrecios { get; set; }
        public virtual tblTipoProductos tblTipoProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductosXProveedor> tblProductosXProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetalleCotizaciones> tblDetalleCotizaciones { get; set; }
    }
}
