//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPermisos()
        {
            this.tblRolPermisos = new HashSet<tblRolPermisos>();
        }
    
        public decimal decIdPermiso { get; set; }
        public string strNombreObjeto { get; set; }
        public string strDescripcion { get; set; }
        public decimal decIdFormularioContenedor { get; set; }
    
        public virtual tblFormularios tblFormularios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRolPermisos> tblRolPermisos { get; set; }
    }
}
