//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductosXProveedor
    {
        public decimal decIdContador { get; set; }
        public decimal decIdProveedor { get; set; }
        public decimal decIdProducto { get; set; }
    
        public virtual tblProductos tblProductos { get; set; }
        public virtual tblProveedores tblProveedores { get; set; }
    }
}
