//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proforma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTipoProductos()
        {
            this.tblProductos = new HashSet<tblProductos>();
        }
    
        public decimal decIdTipoProducto { get; set; }
        public string strTipoProducto { get; set; }
        public Nullable<decimal> decIncrementoPrecio1 { get; set; }
        public Nullable<decimal> decIncrementoPrecio2 { get; set; }
        public Nullable<decimal> decIncrementoPrecio3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductos> tblProductos { get; set; }
    }
}
